"use client";

import type React from "react";
import { ArrowDown, ArrowRight, CheckCircle2, Clock3, Lightbulb, Sparkles } from "lucide-react";

const haberRows = [
  ["yo", "había", "había comido"],
  ["tú", "habías", "habías comido"],
  ["él / ella", "había", "había comido"],
  ["nosotros/as", "habíamos", "habíamos comido"],
  ["vosotros/as", "habíais", "habíais comido"],
  ["ellos/as", "habían", "habían comido"],
];

const participleRows = [
  ["-AR", "-ado", "trabajar → trabajado · estudiar → estudiado"],
  ["-ER / -IR", "-ido", "comer → comido · vivir → vivido"],
];

const tenseRows = [
  ["Pretérito perfecto", "Pasado relacionado con el presente", "Hoy he trabajado mucho"],
  ["Pretérito indefinido", "Acción terminada en el pasado", "Ayer trabajé mucho"],
  ["Pretérito imperfecto", "Hábito, descripción o acción en desarrollo", "Antes trabajaba mucho"],
  ["Pluscuamperfecto", "Acción anterior a un momento pasado", "Cuando llegué, ya había trabajado"],
];

const irregularRows = [
  ["abrir", "abierto"], ["volver", "vuelto"], ["poner", "puesto"], ["ver", "visto"],
  ["romper", "roto"], ["cubrir", "cubierto"], ["decir", "dicho"],
];

function DataTable({ headers, rows }: { headers: string[]; rows: string[][] }) {
  return <div className="w-full overflow-hidden rounded-2xl border border-border/70">
    <div className="grid gap-px bg-border/70 p-px md:hidden">{rows.map((row) => <dl key={row.join("-")} className="grid gap-2 bg-background/90 p-4">{row.map((cell, index) => <div key={`${cell}-${index}`} className={index === 0 ? "border-b border-border/70 pb-2" : "min-w-0"}><dt className="mb-0.5 text-[10px] font-black uppercase tracking-wider text-muted-foreground">{headers[index]}</dt><dd className={`break-words text-sm ${index > 0 ? "font-mono font-medium" : "font-semibold"}`}>{cell}</dd></div>)}</dl>)}</div>
    <table className="hidden w-full table-fixed text-left text-sm md:table lg:text-[15px]"><thead className="bg-muted/50 text-muted-foreground"><tr>{headers.map((header) => <th key={header} className="px-4 py-3 font-bold lg:px-5 lg:py-4">{header}</th>)}</tr></thead><tbody className="divide-y divide-border/70 bg-background/90">{rows.map((row) => <tr key={row.join("-")} className="transition-colors hover:bg-muted/35">{row.map((cell, index) => <td key={`${cell}-${index}`} className={`break-words px-4 py-3 lg:px-5 lg:py-4 ${index > 0 ? "font-mono font-medium" : ""}`}>{cell}</td>)}</tr>)}</tbody></table>
  </div>;
}

function Card({ children, className = "" }: { children: React.ReactNode; className?: string }) {
  return <article className={`rounded-[26px] border border-border/70 bg-muted/10 p-5 shadow-sm sm:p-6 lg:rounded-[30px] lg:p-8 lg:shadow-md ${className}`}>{children}</article>;
}

function SectionTitle({ number, title }: { number: string; title: string }) {
  return <div className="flex items-center gap-3 border-b-2 border-indigo-600 pb-2 lg:col-span-full lg:pb-3"><ArrowRight className="shrink-0 text-indigo-600" size={21} /><h2 className="text-xl font-black tracking-tight sm:text-2xl lg:text-[1.7rem]">{number}. {title}</h2></div>;
}

const Arrow = () => <ArrowDown className="mx-auto my-2 text-indigo-600" size={20} aria-hidden="true" />;

export default function GrammarLesson47() {
  return <main className="w-full space-y-10 bg-background text-foreground sm:space-y-12 lg:mx-auto lg:max-w-6xl lg:space-y-16 2xl:max-w-7xl">
    <section className="rounded-[30px] border border-border/70 bg-muted/15 p-5 shadow-sm sm:p-8 lg:p-10 lg:shadow-md">
      <div className="flex flex-col gap-5 md:flex-row md:items-start md:justify-between"><div className="max-w-3xl"><p className="text-xs font-black uppercase tracking-[0.18em] text-indigo-600">B1.1 · Lesson 47</p><h1 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">El pretérito pluscuamperfecto</h1><p className="mt-3 text-base leading-7 text-muted-foreground sm:text-lg">Aprende a hablar de un pasado anterior a otro pasado.</p></div><Sparkles className="hidden shrink-0 text-indigo-600 md:block" size={42} /></div>
      <div className="mt-7 rounded-2xl border border-indigo-500/20 bg-indigo-500/5 p-4"><h2 className="text-sm font-black uppercase tracking-wider text-indigo-700 dark:text-indigo-300">Objetivo de la lección</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">Identificar y formar el pluscuamperfecto para ordenar acciones pasadas, hablar de experiencias previas y diferenciarlo de otros tiempos del pasado.</p></div>
    </section>

    <section className="space-y-5"><SectionTitle number="1" title="¿Qué es?" /><Card><p className="text-sm leading-7 text-muted-foreground">El pretérito pluscuamperfecto se utiliza para hablar de una acción que ocurrió antes de otra situación o acción en el pasado.</p><div className="mt-5 rounded-2xl border border-indigo-500/30 bg-indigo-500/5 p-5 text-center"><p className="text-xs font-black uppercase tracking-widest text-indigo-600">Idea principal</p><p className="mt-2 text-lg font-bold">Pasado anterior a otro pasado</p></div><div className="mt-5 rounded-2xl border border-border/70 bg-background/80 p-4"><p className="text-sm font-bold">Cuando llegué a la estación, el tren ya había salido.</p><div className="mt-4 grid gap-3 text-sm sm:grid-cols-2"><p className="rounded-xl bg-muted/50 p-3"><b>Primero:</b> El tren salió.</p><p className="rounded-xl bg-muted/50 p-3"><b>Después:</b> Yo llegué a la estación.</p></div><p className="mt-4 text-sm">Por eso usamos:</p><p className="mt-2 text-sm"><b className="font-mono text-indigo-700 dark:text-indigo-300">había salido</b> → acción anterior</p><p className="mt-1 text-sm"><b className="font-mono text-indigo-700 dark:text-indigo-300">llegué</b> → acción posterior</p></div></Card></section>

    <section className="space-y-5"><SectionTitle number="2" title="Formación" /><div className="grid gap-5 lg:grid-cols-2"><Card><p className="text-sm text-muted-foreground">Se forma con:</p><div className="mt-4 rounded-2xl border border-indigo-500/30 bg-indigo-500/5 p-5 text-center"><p className="font-mono text-lg font-bold">haber en imperfecto + participio</p></div><div className="mt-5"><DataTable headers={["Persona", "Haber", "Ejemplo"]} rows={haberRows} /></div></Card><Card><h3 className="text-lg font-bold">Participios</h3><div className="mt-4"><DataTable headers={["Verbos", "Terminación", "Ejemplos"]} rows={participleRows} /></div></Card></div></section>

    <section className="space-y-5 lg:grid lg:grid-cols-[minmax(0,1fr)_19rem] lg:items-start lg:gap-6 lg:space-y-0"><SectionTitle number="3" title="Uso 1: una acción anterior a otra acción pasada" /><Card><p className="text-sm leading-7 text-muted-foreground">Este es el uso más importante. Utilizamos el pluscuamperfecto cuando tenemos dos acciones en el pasado y queremos indicar cuál ocurrió primero.</p><div className="mt-5 rounded-2xl border border-border/70 bg-background/80 p-4"><p className="font-semibold">Cuando llegué a clase, la profesora ya había empezado la lección.</p><p className="mt-4 text-sm font-bold">Orden de las acciones:</p><div className="mt-3 max-w-sm text-sm"><p className="rounded-xl bg-indigo-500/5 p-3">1. La profesora empezó la lección.</p><Arrow /><p className="rounded-xl bg-muted/60 p-3">2. Yo llegué a clase.</p></div><p className="mt-5 text-sm"><b className="font-mono text-indigo-700 dark:text-indigo-300">había empezado</b> → ocurrió primero</p><p className="mt-1 text-sm"><b className="font-mono text-indigo-700 dark:text-indigo-300">llegué</b> → ocurrió después</p></div><h3 className="mt-6 text-lg font-bold">Otros ejemplos</h3><div className="mt-3 grid gap-3 text-sm sm:grid-cols-3">{["Cuando llegué a casa, mi hermano ya había cenado.", "Cuando llamé a Ana, ella ya había terminado el trabajo.", "Cuando llegamos al aeropuerto, el avión ya había salido."].map((item) => <p key={item} className="rounded-xl border border-border/70 bg-background/80 p-4">{item}</p>)}</div></Card><Card className="border-amber-500/30 bg-amber-500/5 lg:sticky lg:top-6"><h3 className="flex items-center gap-2 text-lg font-bold"><Lightbulb className="text-amber-600" size={20} />Palabra muy frecuente: ya</h3><p className="mt-3 text-sm">Cuando llegué, el tren <b>ya había salido</b>.</p><p className="mt-3 text-sm text-muted-foreground"><b>ya + pluscuamperfecto</b> aparece muchísimo en este uso.</p></Card></section>

    <section className="space-y-5 lg:grid lg:grid-cols-[minmax(0,1fr)_22rem] lg:items-start lg:gap-6 lg:space-y-0"><SectionTitle number="4" title="Uso 2: una acción inmediatamente posterior a otra" /><Card><p className="text-sm leading-7 text-muted-foreground">También aparece la idea de una acción posterior a otra, pero con inmediatez y rapidez. Para expresar esto utilizamos normalmente <b>Nada más + infinitivo</b>.</p><div className="mt-5 rounded-2xl border border-indigo-500/30 bg-indigo-500/5 p-5 text-center"><p className="font-mono text-lg font-bold">Nada más + infinitivo</p><p className="mt-2 text-sm text-muted-foreground">Significa inmediatamente después de o en cuanto.</p></div><div className="mt-5 grid gap-3 text-sm sm:grid-cols-3">{["Nada más llegar, llamé a mi madre.", "Nada más terminar el trabajo, salí de la oficina.", "Nada más llegar a casa, me duché.", "Nada más empezar la clase, el profesor explicó el examen."].map((item) => <p key={item} className="rounded-xl border border-border/70 bg-background/80 p-4">{item}</p>)}</div><div className="mt-5 rounded-2xl bg-muted/60 p-4 text-sm"><p><b>Primero:</b> llegué.</p><p className="mt-1"><b>Inmediatamente después:</b> llamé a mi madre.</p></div></Card><Card className="border-amber-500/30 bg-amber-500/5 lg:sticky lg:top-6"><h3 className="text-lg font-bold">Importante</h3><p className="mt-3 text-sm leading-7">En este uso, no usamos necesariamente el pluscuamperfecto. La idea que expresamos es la relación temporal entre dos acciones:</p><p className="mt-4 rounded-xl bg-background/80 p-3 text-sm"><b>Nada más llegar, empecé a estudiar.</b><br /><span className="text-muted-foreground">= Llegué → inmediatamente después empecé a estudiar.</span></p><p className="mt-3 text-sm">Esto contrasta con:</p><p className="mt-2 rounded-xl bg-background/80 p-3 text-sm"><b>Cuando llegué, ya había empezado a estudiar.</b><br /><span className="text-muted-foreground">= Empezar ocurrió antes de llegar.</span></p></Card></section>

    <section className="space-y-5"><SectionTitle number="5" title="Uso 3: una experiencia que nunca había ocurrido antes" /><Card><p className="text-sm leading-7 text-muted-foreground">El pluscuamperfecto también se utiliza para hablar de algo que no había sucedido antes de un momento determinado del pasado.</p><p className="mt-5 text-sm font-semibold">Es muy frecuente con:</p><div className="mt-3 grid grid-cols-2 gap-2 text-sm sm:grid-cols-4">{["nunca", "alguna vez", "antes", "hasta entonces"].map((item) => <p key={item} className="rounded-xl border border-border/70 bg-background/80 px-4 py-3 font-medium">• {item}</p>)}</div><div className="mt-5 rounded-2xl border border-border/70 bg-background/80 p-4"><h3 className="font-bold">Ejemplo</h3><p className="mt-3 text-sm">Antes de viajar a Japón, nunca había comido sushi.</p><div className="mt-4 grid gap-2 text-sm"><p className="rounded-xl bg-muted/60 p-3">Antes del viaje: nunca había comido sushi.</p><Arrow /><p className="rounded-xl bg-indigo-500/5 p-3">Viaje a Japón: comí sushi por primera vez.</p></div><p className="mt-4 text-sm">Por eso decimos: <b>Nunca había comido sushi.</b></p></div><h3 className="mt-6 text-lg font-bold">Otros ejemplos</h3><div className="mt-3 grid gap-3 text-sm sm:grid-cols-3">{["Antes de ese día, nunca había visto la nieve.", "Cuando fui a España, nunca había hablado con un español.", "Antes de empezar el curso, nunca había estudiado español."].map((item) => <p key={item} className="rounded-xl border border-border/70 bg-background/80 p-4">{item}</p>)}</div></Card></section>

    <section className="space-y-5"><SectionTitle number="6" title="Diferencia entre he comido, comí y había comido" /><Card><p className="text-sm leading-7 text-muted-foreground">Esta diferencia es fundamental.</p><div className="mt-5 grid gap-3 text-sm lg:grid-cols-3">{[["Nunca he comido sushi.", "Hasta ahora, nunca he tenido esa experiencia."], ["Nunca comí sushi.", "Presentamos la acción dentro de un período pasado."], ["Nunca había comido sushi.", "Hasta un momento del pasado, nunca había tenido esa experiencia."]].map(([example, explanation]) => <div key={example} className="rounded-2xl border border-border/70 bg-background/80 p-4"><p className="font-bold">{example}</p><p className="mt-2 leading-6 text-muted-foreground">→ {explanation}</p></div>)}</div><h3 className="mt-6 text-lg font-bold">Mira la diferencia</h3><div className="mt-3 grid gap-3 text-sm sm:grid-cols-2"><p className="rounded-xl bg-muted/60 p-4"><b>Nunca he visto esa película.</b><br /><span className="text-muted-foreground">Ahora → todavía no la he visto.</span></p><p className="rounded-xl bg-indigo-500/5 p-4"><b>Antes de ayer, nunca había visto esa película.</b><br /><span className="text-muted-foreground">Aquel momento del pasado → hasta entonces no la había visto.</span></p></div></Card></section>

    <section className="space-y-5"><SectionTitle number="7" title="Comparación rápida de los cuatro tiempos" /><Card><div><DataTable headers={["Tiempo", "Uso principal", "Ejemplo"]} rows={tenseRows} /></div><div className="mt-5 rounded-2xl border border-indigo-500/20 bg-indigo-500/5 p-5"><h3 className="text-lg font-bold">La clave</h3><div className="mt-4 grid gap-2 text-sm sm:grid-cols-2">{[["Perfecto", "pasado → AHORA"], ["Indefinido", "PASADO → terminado"], ["Imperfecto", "contexto / hábito / acción en desarrollo"], ["Pluscuamperfecto", "PASADO ANTERIOR → PASADO"]].map(([name, meaning]) => <p key={name} className="rounded-xl bg-background/80 px-3 py-3"><b>{name}</b><span className="mx-2 text-indigo-600">→</span>{meaning}</p>)}</div></div></Card></section>

    <section className="space-y-5"><SectionTitle number="8" title="Participios irregulares importantes" /><Card><p className="text-sm text-muted-foreground">Son los mismos del pretérito perfecto.</p><div className="mt-5 max-w-2xl"><DataTable headers={["Infinitivo", "Participio pasado"]} rows={irregularRows} /></div><h3 className="mt-6 text-lg font-bold">Ejemplos</h3><div className="mt-3 grid gap-3 text-sm sm:grid-cols-2 lg:grid-cols-4">{["Cuando llegué, ya había hecho los deberes.", "Nunca había visto algo así.", "Ella ya me había dicho la verdad.", "Cuando volví, él ya había puesto la mesa."].map((item) => <p key={item} className="rounded-xl border border-border/70 bg-background/80 p-4">{item}</p>)}</div></Card></section>

    <section className="space-y-5"><SectionTitle number="9" title="Resumen de los tres usos" /><div className="grid gap-5 lg:grid-cols-3">{[["1. Una acción anterior a otra acción pasada", "Cuando llegué, el tren ya había salido.", "salió → llegué"], ["2. Una acción inmediatamente posterior a otra", "Nada más llegar, llamé a mi madre.", "llegué → inmediatamente después → llamé"], ["3. Una experiencia que no había ocurrido antes de un momento pasado", "Antes de viajar a Japón, nunca había comido sushi.", "antes del viaje → nunca había comido sushi → viaje → primera vez"]].map(([title, example, sequence]) => <Card key={title}><h3 className="text-base font-bold leading-6">{title}</h3><p className="mt-4 rounded-xl bg-background/80 p-3 text-sm">{example}</p><p className="mt-4 text-sm font-mono text-indigo-700 dark:text-indigo-300">{sequence}</p></Card>)}</div></section>

    <section className="rounded-[30px] border border-emerald-500/25 bg-emerald-500/5 p-5 sm:p-7"><div className="flex items-start gap-3"><Clock3 className="mt-1 shrink-0 text-emerald-600" size={22} /><div><h2 className="text-2xl font-black">Regla para recordar</h2><p className="mt-3 text-sm leading-7"><b className="font-mono">había + participio</b> = algo que ya había ocurrido / no había ocurrido antes de un momento pasado.</p></div></div><div className="mt-5 grid grid-cols-2 gap-2 text-sm sm:grid-cols-5">{["había comido", "habías visto", "había terminado", "habíamos hecho", "habían salido"].map((item) => <p key={item} className="rounded-xl bg-background/80 px-3 py-3 text-center font-mono font-bold"><CheckCircle2 className="mr-1 inline text-emerald-600" size={15} />{item}</p>)}</div></section>
  </main>;
}
