/* eslint-disable */
// This file is auto-generated by `scripts/generate-vocabulary-index.mjs`.
// Do not edit manually.

import type { VocabularyCollection } from "../utils"
import c0 from "./collection_1"
import c1 from "./collection_2"
import c2 from "./collection_3"
import c3 from "./collection_4"
import c4 from "./collection_5"
import c5 from "./collection_6"
import c6 from "./collection_7"
import c7 from "./collection_8"
import c8 from "./collection_9"
import c9 from "./collection_10"
import c10 from "./collection_11"
import c11 from "./collection_12"
import c12 from "./collection_13"
import c13 from "./collection_14"
import c14 from "./collection_15"
import c15 from "./collection_16"
import c16 from "./collection_17"
import c17 from "./collection_18"
import c18 from "./collection_19"
import c19 from "./collection_20"
import c20 from "./collection_21"
import c21 from "./collection_22"
import c22 from "./collection_23"
import c23 from "./collection_24"
import c24 from "./collection_25"
import c25 from "./collection_26"
import c26 from "./collection_27"
import c27 from "./collection_28"
import c28 from "./collection_29"
import c29 from "./collection_30"
import c30 from "./collection_31"
import c31 from "./collection_32"
import c32 from "./collection_33"
import c33 from "./collection_34"
import c34 from "./collection_35"
import c35 from "./collection_36"
import c36 from "./collection_37"
import c37 from "./collection_38"
import c38 from "./collection_39"
import c39 from "./collection_40"
import c40 from "./collection_41"
import c41 from "./collection_42"
import c42 from "./collection_43"
import c43 from "./collection_44"
import c44 from "./collection_45"
import c45 from "./collection_46"
import c46 from "./collection_47"
import c47 from "./collection_48"
import c48 from "./collection_49"
import c49 from "./collection_50"
import c50 from "./collection_51"
import c51 from "./collection_52"
import c52 from "./collection_53"
import c53 from "./collection_54"
import c54 from "./collection_55"

export const VOCABULARY_COLLECTIONS: VocabularyCollection[] = [
  c0,
  c1,
  c2,
  c3,
  c4,
  c5,
  c6,
  c7,
  c8,
  c9,
  c10,
  c11,
  c12,
  c13,
  c14,
  c15,
  c16,
  c17,
  c18,
  c19,
  c20,
  c21,
  c22,
  c23,
  c24,
  c25,
  c26,
  c27,
  c28,
  c29,
  c30,
  c31,
  c32,
  c33,
  c34,
  c35,
  c36,
  c37,
  c38,
  c39,
  c40,
  c41,
  c42,
  c43,
  c44,
  c45,
  c46,
  c47,
  c48,
  c49,
  c50,
  c51,
  c52,
  c53,
  c54,
]
